# Generated by Django 5.2.5 on 2025-09-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('retirada', models.BooleanField(default=False)),
                ('pagamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('Media', 'Média'), ('Grande', 'Grande'), ('Big', 'Big'), ('Calzone', 'Calzone')], max_length=20)),
                ('sabores', models.TextField(help_text='Lista de sabores separados por vírgula')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pi.pedido')),
            ],
        ),
    ]
