# Generated by Django 5.2.5 on 2025-09-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
