# Generated by Django 5.2.5 on 2025-10-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0003_remove_usuario_username_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
