# Generated by Django 5.2.5 on 2025-10-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
